# Use postgres/example user/password credentials
version: '3.1'

services:

  pgsql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_NAME}
    ports:
      - 5432:5432
    
  userauth:
    image: machinenotlearning/userauth:latest
    environment: 
      DATASOURCE_URL: jdbc:postgresql://pgsql:5432/${PG_NAME}
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: ${PG_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_PROFILES_ACTIVE: local
    ports:
      - 8180:8080
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  redis: 
    image: redis
    ports:
      - 6379:6379