# Use postgres/example user/password credentials
version: '3.1'

services:

  pgsql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_NAME}
    ports:
      - 5432:5432
    
  userauth:
    image: userauth:0.0.1-SNAPSHOT 
    environment: 
      DATASOURCE_URL: jdbc:postgresql://pgsql:5432/${PG_NAME}
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: ${PG_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_PROFILES_ACTIVE: local
    ports:
      - 8180:8080