# Use postgres/example user/password credentials
version: '3.1'

services:

  pgsql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_NAME}